# Generated by Django 2.2.1 on 2019-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('your_location', models.CharField(choices=[('choose', 'Choose'), ('bangalore', 'Bangalore'), ('odisha', 'Odisha'), ('hyderabad', 'Hyderabad'), ('pune', 'Pune')], default='choose', max_length=10)),
                ('current_address', models.CharField(max_length=64)),
                ('language', models.CharField(choices=[('choose', 'Choose'), ('hindi', 'Hindi'), ('english', 'English')], default='choose', max_length=10)),
                ('Nationality', models.CharField(choices=[('choose', 'Choose'), ('india', 'India'), ('us', 'US'), ('japan', 'Japan'), ('austrelia', 'Austrelia')], default='choose', max_length=10)),
                ('qualification', models.CharField(choices=[('choose', 'Choose'), ('bca', 'BCA'), ('mca', 'MCA'), ('btech', 'BTECH')], default='choose', max_length=10)),
                ('year_of_passout', models.CharField(choices=[('choose', 'Choose'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016')], default='choose', max_length=10)),
                ('DOB', models.DateField()),
                ('workingexpfrom', models.DateField()),
                ('workingexpto', models.DateField()),
                ('Job_Type', models.CharField(choices=[('choose', 'Choose'), ('full_time', 'Full_Time'), ('part_time', 'Part_Time')], default='choose', max_length=10)),
            ],
        ),
    ]
