# Generated by Django 2.2.1 on 2019-09-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opprtunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Type', models.CharField(choices=[('choose', 'Choose'), ('full_time', 'Full_Time'), ('part_time', 'Part_Time')], default='choose', max_length=10)),
                ('Posting_title', models.CharField(choices=[('choose', 'Choose'), ('python_developer', 'Python_Developer'), ('web_developer', 'Web_Developer'), ('javascript_developer', 'JavaScript_Developer'), ('ai', 'AI'), ('machine_learning', 'Machine_Learning')], default='choose', max_length=10)),
                ('Date_opened', models.DateField()),
                ('city', models.CharField(choices=[('choose', 'Choose'), ('hyderabad', 'Hyderabad'), ('bangalore', 'Bangalore'), ('kolkata', 'Kolkata'), ('bhubaneswar', 'Bhubaneswar')], default='choose', max_length=10)),
            ],
        ),
    ]
